/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AgreementsIdRouteImport } from './routes/agreements.$id'
import { Route as AgreementsNewRouteImport } from './routes/agreements.new'
import { Route as ApiPrepareEvidenceRouteImport } from './routes/api.prepare-evidence'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesIdRouteImport } from './routes/cases.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementsIdRoute = AgreementsIdRouteImport.update({
  id: '/agreements/$id',
  path: '/agreements/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementsNewRoute = AgreementsNewRouteImport.update({
  id: '/agreements/new',
  path: '/agreements/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrepareEvidenceRoute = ApiPrepareEvidenceRouteImport.update({
  id: '/api/prepare-evidence',
  path: '/api/prepare-evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRoute,
} as any)
const CasesIdRoute = CasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/agreements/$id': typeof AgreementsIdRoute
  '/agreements/new': typeof AgreementsNewRoute
  '/api/prepare-evidence': typeof ApiPrepareEvidenceRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/agreements/$id': typeof AgreementsIdRoute
  '/agreements/new': typeof AgreementsNewRoute
  '/api/prepare-evidence': typeof ApiPrepareEvidenceRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases': typeof CasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/agreements/$id': typeof AgreementsIdRoute
  '/agreements/new': typeof AgreementsNewRoute
  '/api/prepare-evidence': typeof ApiPrepareEvidenceRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/dashboard'
    | '/how-it-works'
    | '/agreements/$id'
    | '/agreements/new'
    | '/api/prepare-evidence'
    | '/cases/$id'
    | '/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/agreements/$id'
    | '/agreements/new'
    | '/api/prepare-evidence'
    | '/cases/$id'
    | '/cases'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/dashboard'
    | '/how-it-works'
    | '/agreements/$id'
    | '/agreements/new'
    | '/api/prepare-evidence'
    | '/cases/$id'
    | '/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  HowItWorksRoute: typeof HowItWorksRoute
  AgreementsIdRoute: typeof AgreementsIdRoute
  AgreementsNewRoute: typeof AgreementsNewRoute
  ApiPrepareEvidenceRoute: typeof ApiPrepareEvidenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreements/$id': {
      id: '/agreements/$id'
      path: '/agreements/$id'
      fullPath: '/agreements/$id'
      preLoaderRoute: typeof AgreementsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreements/new': {
      id: '/agreements/new'
      path: '/agreements/new'
      fullPath: '/agreements/new'
      preLoaderRoute: typeof AgreementsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prepare-evidence': {
      id: '/api/prepare-evidence'
      path: '/api/prepare-evidence'
      fullPath: '/api/prepare-evidence'
      preLoaderRoute: typeof ApiPrepareEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/$id': {
      id: '/cases/$id'
      path: '/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof CasesIdRouteImport
      parentRoute: typeof CasesRoute
    }
  }
}

interface CasesRouteChildren {
  CasesIdRoute: typeof CasesIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesIdRoute: CasesIdRoute,
  CasesIndexRoute: CasesIndexRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  HowItWorksRoute: HowItWorksRoute,
  AgreementsIdRoute: AgreementsIdRoute,
  AgreementsNewRoute: AgreementsNewRoute,
  ApiPrepareEvidenceRoute: ApiPrepareEvidenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
